### ISSUE TITLE
NLP input requirements

### ISSUE THREAD

**Issue by diatomsRcool** [helxplatform/dbgaptools#2]
We need to know the specification for Index I in order to build the data dictionary parser. In order to create the specification for [Index I](https://docs.google.com/document/d/1wiEby3kn7uDvB7lJQ1FiE2VVt_8LS6JIkESZo2h_E-g/edit#), we need to know what the input requirements are for the NLP tool. What should be harvested from the data dictionary for the NLP tool?

**Comment by diatomsRcool** [comment]
From @kwuichet What to parse: variable description, name, encoded type, also parse dataset information which can also tell more about variable

**Comment by diatomsRcool** [comment]
From April WG call: must contain
free text variable description
variable name (text)
encoded values (categorical values key)
data set description (text)

**Comment by diatomsRcool** [comment]
@kwuichet @RobertJCarroll 
Is everything you need mentioned somewhere above?

**Comment by kwuichet** [comment]
To run NLP we only need the text description, but in order to keep track of the data and link everything back together it would be best to have the accessions for the variable (phv), dataset (pht), and study (phs) files in addition to the basic text data. Also, any units of measure associated with the variable when available.

**Comment by diatomsRcool** [comment]
From @kwuichet  NLP input is the variable description text, but other information from the data dictionary file (measurement, etc.) can be meaningful for parsing/interpreting.
