### ISSUE TITLE
file naming conventions for parser output

### ISSUE THREAD

**Issue by diatomsRcool** [helxplatform/dbgaptools#8]
I'm assuming that the parser will generate a separate output file for every data dictionary.

Ben and I propose:

YYYYMMDDhhmmss_phsfull accession_phtfull accession_ddparse.json

Please comment with your thoughts.

**Comment by alexwaldrop** [comment]
@diatomsRcool @bheavner Wanted to clarify the issue bit. Are you proposing to hard code these rules into the parser? At present the tool lets you specify the absolute path of the output file to maximize flexibility. My thinking here was that we could have external tools calling the parser (WDL task, external script, etc.) apply whatever naming convention rules without having to build those rules into the parser itself. Would make things easier if we needed to change rules at some point or have different rules in different contexts because we wouldn't need to build a new parser. That said, I can totally hard code these conventions into the tool if we need but wanted to explain the design decision. What are your thoughts?

**Comment by bheavner** [comment]
I agree that it's good to have the parser take the output path as a parameter, not to hardcode the convention. But we should document the convention. Perhaps make the convention a default value if the path isn't provided as an argument?

**Comment by diatomsRcool** [comment]
@bheavner I'm guessing we'll need to make a separate "STAGE file naming conventions" document

**Comment by bheavner** [comment]
Yes, and that's beyond the scope of this particular development effort - that'll be in the Data Harmonization WG's court.

**Comment by alexwaldrop** [comment]
I think the default behavior is a great compromise. I can definitely build that into the tool.

**Comment by diatomsRcool** [comment]
I'm going to close this issue. The naming convention is listed [here](https://github.com/nhlbidatastage/standardsandspecs/blob/master/file_naming_conventions.md)
If there are any problems with the file naming convention, file an issue in the standardsandspecs repo.
